app = "scholarx-backend"
primary_region = "fra"

kill_signal = "SIGINT"
kill_timeout = 120

[http_service]
  http_service = true
  internal_port = 8000
  protocol = "tcp"
  force_https = true

  [http_service.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 90

  [[http_service.ports]]
    port = "80"
    handlers = ["http"]
  [[http_service.ports]]
    port = "443"
    handlers = ["tls", "http"]
  
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    timeout = "5s"
    headers = { X-Forwarded-Proto = "https" }

[build]
  dockerfile = "Dockerfile"

[env]
  HOST = "0.0.0.0"
  PORT = "8000"
  API_VERSION = "/api/v1"
  MODE = "prod"
  ALGORITHM = "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES = "60"
  REDIS_HOST = "localhost"
  REDIS_PORT = "6379"

[deploy]
  strategy = "bluegreen"
  release_command = "alembic upgrade head"