version: 1
disable_existing_loggers: False
formatters:
  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(levelname)s %(name)s %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: json
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: json
    filename: logout.log
  kafka:
    (): app.core.kafka_handler.KafkaHandler
    level: INFO
    formatter: json
    topic: scholarx-logs
loggers:
  root:
    level: INFO
    handlers: [file, kafka]
    propagate: False  # Prevent propagation to avoid duplicates
  app:  # Add app-specific logger
    level: INFO
    handlers: [file, kafka]
    propagate: False
